#!/usr/bin/env bash
# Changes localhost and facebook.com IP mappings

sudo sed -i 's/127.0.0.1/127.0.0.2/g' /etc/hosts
sudo sed -i '/facebook.com/d' /etc/hosts
echo "8.8.8.8 facebook.com" | sudo tee -a /etc/hosts > /dev/null
